"""V18

Revision ID: 0092496dbe3e
Revises: a9341c0bdffe
Create Date: 2017-08-01 13:48:21.196201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0092496dbe3e'
down_revision = 'a9341c0bdffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excersises', sa.Column('rest', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excersises', 'rest')
    # ### end Alembic commands ###
