"""V19_cosmeticfixes

Revision ID: 047799ebebfd
Revises: 0092496dbe3e
Create Date: 2017-08-01 14:06:59.344796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047799ebebfd'
down_revision = '0092496dbe3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('lastchanged', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('is_cancelled', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_cancelled')
    op.drop_column('articles', 'lastchanged')
    # ### end Alembic commands ###
