"""V32_course_additionalfields

Revision ID: 0ea3df425f16
Revises: 87056f791b99
Create Date: 2017-08-14 12:38:26.779519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea3df425f16'
down_revision = '87056f791b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('griptype', sa.Text(), nullable=True))
    op.add_column('elements', sa.Column('onerepis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elements', 'onerepis')
    op.drop_column('elements', 'griptype')
    # ### end Alembic commands ###
