"""V23_courseauthor

Revision ID: 12526b121e1d
Revises: 4dddebcb8ab4
Create Date: 2017-08-04 14:19:54.990087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12526b121e1d'
down_revision = '4dddebcb8ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
