"""V38_subscrprice

Revision ID: 1fbd172a3b81
Revises: 655e82794af6
Create Date: 2017-09-01 15:31:55.085122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbd172a3b81'
down_revision = '655e82794af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'price')
    # ### end Alembic commands ###
