"""V38_paymentsstatus

Revision ID: 1fbed3d78efe
Revises: 7b9a274a2805
Create Date: 2017-08-31 14:55:40.152229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbed3d78efe'
down_revision = '7b9a274a2805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('status', sa.Enum('new', 'failed', 'confirmed', 'pending'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'status')
    # ### end Alembic commands ###
