"""Sec rev

Revision ID: 264965c2c476
Revises: 0e34bce33bdb
Create Date: 2017-07-19 17:15:20.615859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264965c2c476'
down_revision = '0e34bce33bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('testcolumn', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'testcolumn')
    # ### end Alembic commands ###
