"""V24_courseprice

Revision ID: 284a2478d290
Revises: 12526b121e1d
Create Date: 2017-08-09 11:59:34.125286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284a2478d290'
down_revision = '12526b121e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'price')
    # ### end Alembic commands ###
