"""V38_paymentdescr

Revision ID: 2c91fab23c54
Revises: 54ffde84dfe3
Create Date: 2017-09-01 17:29:39.763367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c91fab23c54'
down_revision = '54ffde84dfe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('descr', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'descr')
    # ### end Alembic commands ###
