"""V34_course_additionalfields

Revision ID: 2d24047da9ac
Revises: 8c861d1380cf
Create Date: 2017-08-14 22:59:40.340702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d24047da9ac'
down_revision = '8c861d1380cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('lemtype', sa.Enum('course', 'week', 'workout', 'round', 'exc'), nullable=True))
    op.drop_column('elements', 'elemtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('elemtype', mysql.ENUM(u'course', u'week', u'workout', u'excercise', collation=u'utf8_unicode_ci'), nullable=True))
    op.drop_column('elements', 'lemtype')
    # ### end Alembic commands ###
