"""Thrd rev

Revision ID: 3c1d8104fb9c
Revises: 264965c2c476
Create Date: 2017-07-19 17:16:47.443615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c1d8104fb9c'
down_revision = '264965c2c476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'testcolumn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('testcolumn', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
