"""Ffth rev

Revision ID: 3c3dfeb27069
Revises: d6def953d004
Create Date: 2017-07-19 17:41:55.538151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3dfeb27069'
down_revision = 'd6def953d004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weeks', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weeks', 'comments')
    # ### end Alembic commands ###
