"""V26_courseflags

Revision ID: 3d211c48d5bb
Revises: b7f414e13677
Create Date: 2017-08-09 12:18:47.017411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d211c48d5bb'
down_revision = 'b7f414e13677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_archived', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('lastchanged', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'lastchanged')
    op.drop_column('courses', 'is_archived')
    # ### end Alembic commands ###
