"""V22_articleauthorrelation

Revision ID: 4dddebcb8ab4
Revises: e55390d16a79
Create Date: 2017-08-02 20:20:23.180702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dddebcb8ab4'
down_revision = 'e55390d16a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
