"""sixth

Revision ID: 5065adebbe16
Revises: 3c3dfeb27069
Create Date: 2017-07-24 16:49:07.404058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5065adebbe16'
down_revision = '3c3dfeb27069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_courses_author_id_users'), 'courses', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_courses_author_id_users'), 'courses', type_='foreignkey')
    op.drop_column('courses', 'author_id')
    # ### end Alembic commands ###
