"""V25_courseimage

Revision ID: 535c0940ce17
Revises: 284a2478d290
Create Date: 2017-08-09 12:00:35.660809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535c0940ce17'
down_revision = '284a2478d290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('headerimage', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'headerimage')
    # ### end Alembic commands ###
