"""V37_paymentstatus

Revision ID: 56006f746620
Revises: 38088e8bf431
Create Date: 2017-08-31 14:51:51.086078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56006f746620'
down_revision = '38088e8bf431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
