"""V21_articlearchived

Revision ID: 63cde17acb32
Revises: 660fb808a13d
Create Date: 2017-08-01 17:07:03.397960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cde17acb32'
down_revision = '660fb808a13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_archived', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_archived')
    # ### end Alembic commands ###
