"""V38_subscronetoone1

Revision ID: 655e82794af6
Revises: f29a722add26
Create Date: 2017-08-31 17:52:24.802677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655e82794af6'
down_revision = 'f29a722add26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
