"""V20_articlepreview

Revision ID: 660fb808a13d
Revises: 047799ebebfd
Create Date: 2017-08-01 16:30:04.841471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660fb808a13d'
down_revision = '047799ebebfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('preview', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'preview')
    # ### end Alembic commands ###
