"""V38_paymentcomments

Revision ID: 7b9a274a2805
Revises: 93d45b649ada
Create Date: 2017-08-31 14:54:47.088901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9a274a2805'
down_revision = '93d45b649ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'comments')
    # ### end Alembic commands ###
