"""V36_subscr_lastchanged

Revision ID: 854dfb669f7e
Revises: a9d9588b8986
Create Date: 2017-08-24 17:32:19.266970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854dfb669f7e'
down_revision = 'a9d9588b8986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('lastchanged', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'lastchanged')
    # ### end Alembic commands ###
