"""V38_subscrtype

Revision ID: 85825d39c889
Revises: 1fbd172a3b81
Create Date: 2017-09-01 15:46:46.037913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85825d39c889'
down_revision = '1fbd172a3b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptiontypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscrtype', sa.Enum('short', 'onemonth', 'sixmonths', 'oneyear'), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptiontypes'))
    )
    op.add_column(u'subscriptions', sa.Column('subscrtype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_subscriptions_subscrtype_id_subscriptiontypes'), 'subscriptions', 'subscriptiontypes', ['subscrtype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_subscriptions_subscrtype_id_subscriptiontypes'), 'subscriptions', type_='foreignkey')
    op.drop_column(u'subscriptions', 'subscrtype_id')
    op.drop_table('subscriptiontypes')
    # ### end Alembic commands ###
