"""V28_excers_perftime

Revision ID: 8648faa97753
Revises: d269b4aaa932
Create Date: 2017-08-10 15:45:54.374478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8648faa97753'
down_revision = 'd269b4aaa932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excersises', sa.Column('perftime', sa.String(length=200), nullable=True))
    op.add_column('excersises', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excersises', 'time')
    op.drop_column('excersises', 'perftime')
    # ### end Alembic commands ###
