"""V31_course_tree_clean

Revision ID: 87056f791b99
Revises: d2c4a25c3c1d
Create Date: 2017-08-11 17:48:32.622890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87056f791b99'
down_revision = 'd2c4a25c3c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('flags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'flags')
    # ### end Alembic commands ###
