"""V33_course_additionalfields

Revision ID: 8c861d1380cf
Revises: 0ea3df425f16
Create Date: 2017-08-14 22:37:11.269609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c861d1380cf'
down_revision = '0ea3df425f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
