"""V38_paymentstatus

Revision ID: 93d45b649ada
Revises: 56006f746620
Create Date: 2017-08-31 14:53:29.810695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d45b649ada'
down_revision = '56006f746620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
