"""V29_course_tree

Revision ID: a24e5727c770
Revises: 8648faa97753
Create Date: 2017-08-11 16:20:19.563417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24e5727c770'
down_revision = '8648faa97753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
