"""V14_ispaused

Revision ID: a9abe302ac42
Revises: 53c33b570c6c
Create Date: 2017-07-26 13:29:27.394829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9abe302ac42'
down_revision = '53c33b570c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_paused', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_paused')
    # ### end Alembic commands ###
