"""V35_course_additionalfields

Revision ID: a9d9588b8986
Revises: 2d24047da9ac
Create Date: 2017-08-14 22:59:55.291284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9d9588b8986'
down_revision = '2d24047da9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('elemtype', sa.Enum('course', 'week', 'workout', 'round', 'exc'), nullable=True))
    op.drop_column('elements', 'lemtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('lemtype', mysql.ENUM(u'course', u'week', u'workout', u'round', u'exc', collation=u'utf8_unicode_ci'), nullable=True))
    op.drop_column('elements', 'elemtype')
    # ### end Alembic commands ###
