"""V38_coursefinalrest

Revision ID: adc7d1d4f9e8
Revises: d2f296afa40b
Create Date: 2017-09-05 01:17:02.839623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc7d1d4f9e8'
down_revision = 'd2f296afa40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('finalrest', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elements', 'finalrest')
    # ### end Alembic commands ###
