"""V38_paymentsubscrbackref

Revision ID: bc0405ac90ab
Revises: 1fbed3d78efe
Create Date: 2017-08-31 16:17:03.847489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0405ac90ab'
down_revision = '1fbed3d78efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
