"""V38_coursecustomorder

Revision ID: c3d72ea285f6
Revises: adc7d1d4f9e8
Create Date: 2017-09-06 15:31:51.055231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d72ea285f6'
down_revision = 'adc7d1d4f9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('customorder', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elements', 'customorder')
    # ### end Alembic commands ###
