"""V38_subscrispaid

Revision ID: c3e9c0c9950c
Revises: e2a9d122c361
Create Date: 2017-08-31 16:24:36.906642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e9c0c9950c'
down_revision = 'e2a9d122c361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_paid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_paid')
    # ### end Alembic commands ###
