"""V9_subscr

Revision ID: c600913fa8af
Revises: f108b153b1fb
Create Date: 2017-07-24 17:46:48.947302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c600913fa8af'
down_revision = 'f108b153b1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'comments')
    # ### end Alembic commands ###
