"""V38_subscrcourseid

Revision ID: c7b56173b6d6
Revises: c3e9c0c9950c
Create Date: 2017-08-31 16:35:52.021282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b56173b6d6'
down_revision = 'c3e9c0c9950c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
