"""V27_coursenameheader

Revision ID: d269b4aaa932
Revises: b29c16a5664f
Create Date: 2017-08-09 21:09:55.626983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd269b4aaa932'
down_revision = 'b29c16a5664f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('header', sa.String(length=200), nullable=True))
    op.drop_column('courses', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200), nullable=True))
    op.drop_column('courses', 'header')
    # ### end Alembic commands ###
