"""V30_course_tree

Revision ID: d2c4a25c3c1d
Revises: a24e5727c770
Create Date: 2017-08-11 17:37:18.038419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2c4a25c3c1d'
down_revision = 'a24e5727c770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Integer(), nullable=True),
    sa.Column('lastchanged', sa.DateTime(), nullable=False),
    sa.Column('headerimage', sa.Text(), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('elemtype', sa.Enum('course', 'week', 'workout', 'excercise'), nullable=True),
    sa.Column('weektype', sa.Enum('power', 'endurance', 'fingers', 'projecting', 'rest', 'test'), nullable=True),
    sa.Column('descr', sa.Text(), nullable=True),
    sa.Column('timetotal', sa.String(length=200), nullable=True),
    sa.Column('numreps', sa.Integer(), nullable=True),
    sa.Column('numsets', sa.Integer(), nullable=True),
    sa.Column('resttime', sa.Text(), nullable=True),
    sa.Column('perftime', sa.String(length=200), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_elements_author_id_users')),
    sa.ForeignKeyConstraint(['parent_id'], [u'elements.id'], name=op.f('fk_elements_parent_id_elements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elements'))
    )
    op.drop_table('excersise_workout_association')
    op.drop_table('courses')
    op.drop_table('workout_week_association')
    op.drop_table('weeks')
    op.drop_table('excersises')
    op.drop_table('workouts')
    op.drop_table('week_course_association')
    op.drop_constraint(u'fk_media_excercise_id_excersises', 'media', type_='foreignkey')
    op.create_foreign_key(op.f('fk_media_excercise_id_elements'), 'media', 'elements', ['excercise_id'], ['id'])
    op.drop_constraint(u'fk_subscriptions_course_id_courses', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_course_id_elements'), 'subscriptions', 'elements', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_subscriptions_course_id_elements'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(u'fk_subscriptions_course_id_courses', 'subscriptions', 'courses', ['course_id'], ['id'])
    op.drop_constraint(op.f('fk_media_excercise_id_elements'), 'media', type_='foreignkey')
    op.create_foreign_key(u'fk_media_excercise_id_excersises', 'media', 'excersises', ['excercise_id'], ['id'])
    op.create_table('week_course_association',
    sa.Column('weeks_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('courses_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['courses_id'], [u'courses.id'], name=u'fk_week_course_association_courses_id_courses'),
    sa.ForeignKeyConstraint(['weeks_id'], [u'weeks.id'], name=u'fk_week_course_association_weeks_id_weeks'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('workouts',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200), nullable=True),
    sa.Column('descr', mysql.MEDIUMTEXT(collation=u'utf8_unicode_ci'), nullable=True),
    sa.Column('time', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('excersises',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200), nullable=True),
    sa.Column('descr', mysql.MEDIUMTEXT(collation=u'utf8_unicode_ci'), nullable=True),
    sa.Column('numreps', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('numsets', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('comments', mysql.MEDIUMTEXT(collation=u'utf8_unicode_ci'), nullable=True),
    sa.Column('rest', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True),
    sa.Column('perftime', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200), nullable=True),
    sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('weeks',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200), nullable=True),
    sa.Column('comments', mysql.MEDIUMTEXT(collation=u'utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('workout_week_association',
    sa.Column('workouts_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('weeks_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['weeks_id'], [u'weeks.id'], name=u'fk_workout_week_association_weeks_id_weeks'),
    sa.ForeignKeyConstraint(['workouts_id'], [u'workouts.id'], name=u'fk_workout_week_association_workouts_id_workouts'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('courses',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_published', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('headerimage', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True),
    sa.Column('preview', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True),
    sa.Column('is_archived', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lastchanged', mysql.DATETIME(), nullable=False),
    sa.Column('header', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'users.id'], name=u'fk_courses_author_id_users'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('excersise_workout_association',
    sa.Column('excersise_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('workout_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excersise_id'], [u'excersises.id'], name=u'fk_excersise_workout_association_excersise_id_excersises'),
    sa.ForeignKeyConstraint(['workout_id'], [u'workouts.id'], name=u'fk_excersise_workout_association_workout_id_workouts'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('elements')
    # ### end Alembic commands ###
