"""Frth rev

Revision ID: d6def953d004
Revises: 3c1d8104fb9c
Create Date: 2017-07-19 17:40:38.108623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6def953d004'
down_revision = '3c1d8104fb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
