"""V38_coursecustomorderstr

Revision ID: debb0b8553a3
Revises: c3d72ea285f6
Create Date: 2017-09-06 15:45:14.267321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debb0b8553a3'
down_revision = 'c3d72ea285f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
