"""V38_subscrdeletecascade

Revision ID: e2a9d122c361
Revises: bc0405ac90ab
Create Date: 2017-08-31 16:21:31.332997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a9d122c361'
down_revision = 'bc0405ac90ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
