"""V21_headerimage

Revision ID: e55390d16a79
Revises: 63cde17acb32
Create Date: 2017-08-02 19:23:07.924286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55390d16a79'
down_revision = '63cde17acb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('headerimage', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'headerimage')
    # ### end Alembic commands ###
