"""V11_movetoutf8

Revision ID: e95a9d889c86
Revises: 72dddaa36bcc
Create Date: 2017-07-25 16:45:03.723723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95a9d889c86'
down_revision = '72dddaa36bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
