"""V38_subscronetoone

Revision ID: f29a722add26
Revises: c7b56173b6d6
Create Date: 2017-08-31 17:51:32.456898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29a722add26'
down_revision = 'c7b56173b6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
